# Generated by Django 4.2.4 on 2023-08-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Natal_First_Time_Table',
        ),
    ]
