# Generated by Django 4.2.4 on 2023-09-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Natal_First_Time_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_No', models.IntegerField(default=0, verbose_name='Serial No.')),
                ('name', models.CharField(db_column='Name ', default='', max_length=100, verbose_name='Name')),
                ('gender', models.CharField(db_column='gender', default='', max_length=100, verbose_name='gender')),
                ('father_name', models.CharField(db_column='father name', default='', max_length=100, verbose_name='father name')),
                ('mother_name', models.CharField(db_column='mother name', default='', max_length=100, verbose_name='mother name')),
                ('dob', models.CharField(db_column='dob', default='', max_length=50, verbose_name='dob')),
                ('time', models.CharField(db_column='time ', default='', max_length=100, verbose_name='time')),
                ('location_search_input_lord', models.CharField(db_column='location-search-input', default='', max_length=200, verbose_name='location-search-input')),
                ('timezone', models.CharField(db_column='Time Zone', default='', max_length=100, verbose_name='Time Zone')),
                ('dst', models.CharField(db_column='DST', default='', max_length=100, verbose_name='DST')),
                ('date1', models.CharField(db_column='BTR Date and Time', default='', max_length=100, verbose_name='BTR Date and Time')),
                ('currentaddress', models.CharField(db_column='BTR Place', default='', max_length=200, verbose_name='BTR Place')),
            ],
            options={
                'verbose_name': '100. Table Name: Natal First Time Table (Table Code:100)',
                'verbose_name_plural': '100. Table Name:  Natal First Time Table (Table Code:100)',
            },
        ),
        migrations.CreateModel(
            name='User_Registration_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name ', default='', max_length=100, verbose_name='name')),
                ('city', models.CharField(db_column='city', default='', max_length=100, verbose_name='city')),
                ('mobile_number', models.CharField(db_column='mobile number', default='', max_length=100, verbose_name='mobile_number')),
                ('Email', models.CharField(db_column='Email', default='', max_length=100, verbose_name='Email')),
                ('Password', models.CharField(db_column='password', default='', max_length=50, verbose_name='password')),
                ('Forgot_password', models.CharField(db_column='forgot password ', default='', max_length=100, verbose_name='forgot password')),
                ('Reset_password', models.CharField(db_column='reset password', default='', max_length=200, verbose_name='reset password')),
            ],
            options={
                'verbose_name': '100. Table Name: User_Registration_Table (Table Code:101)',
                'verbose_name_plural': '100. Table Name:  User_Registration_Table (Table Code:101)',
            },
        ),
        migrations.CreateModel(
            name='User_Setting_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphtype', models.CharField(db_column='graphtype', default='', max_length=100, verbose_name='graphtype')),
                ('language', models.CharField(db_column='language', default='', max_length=100, verbose_name='language')),
                ('color', models.CharField(db_column='color', default='', max_length=100, verbose_name='color')),
                ('font_size', models.CharField(db_column='font-size', default='', max_length=200, verbose_name='font-size')),
                ('bgColor', models.CharField(db_column='bgColor', default='', max_length=100, verbose_name='bgColor')),
                ('chartColor', models.CharField(db_column='chartColor', default='', max_length=100, verbose_name='chartColor')),
                ('glyphColor', models.CharField(db_column='glyphColor', default='', max_length=100, verbose_name='glyphColor')),
            ],
            options={
                'verbose_name': '100. Table Name: User_Setting_Table (Table Code:101)',
                'verbose_name_plural': '100. Table Name:  User_Setting_Table (Table Code:101)',
            },
        ),
    ]
